# Axiu-Plugin 配置文件

api:
  #使用的平台，0：test_nine；1：ttocr.com；2：2captcha.com
  type: ${api_type}
  #使用的api(test_nine、ttocr、2captcha必填)，例：https://api.example.com/recognize
  api: ${api_api}
  #使用的resapi(ttocr、2captcha必填)，例：https://api.example.com/results
  resapi: ${api_resapi}
  #api、resapi需要的key(ttocr、2captcha必填)，例: appkey=***
  key: ${api_key}
  #api需要的其他参数(除"key、gt、challenge"以外的，ttocr、2captcha必填)，例: referer=***
  query: ${api_query}
  #resapi需要的其他参数(除"key"以外的，2captcha必填)，例: action=***
  resquery: ${api_resquery}

  # 是否启动内置打码服务（关闭后可用他人服务或不使用手动打码）
  startApi: ${api_startApi}
  # 内置打码服务监听端口
  Port: ${api_Port}
  # 发送给用户的打码链接前缀，必须是用户设备能访问到的地址
  Address: ${api_Address}
  # Bot 提交验证码的地址，用自己的服务保持默认即可，用他人的按对方提供填写
  verifyAddr: ${api_verifyAddr}

  # 0:仅手动；1:仅自动；2:自动失败换手动
  GtestType: ${api_GtestType}

  # 是否启用扫码登录功能（仅master可用）
  qrLogin_enabled: ${api_qrLogin_enabled}
